name: adaptive_layout_one
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  url_strategy: ^0.2.0 
  flutter_adaptive_scaffold: ^0.1.5
  go_router: ^8.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.5
  lint: ^2.1.2

  go_router_builder: ^2.1.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
